### ISSUE TITLE
로그인이 안되는데 뭐가 문제인지 모르겠어요

### ISSUE THREAD

**Issue by heeboom** [magenta1028/hideSpamBot#1]
Error: Session closed before response #2

(node:18224) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'DEVICE_NOT_REGISTERED' of undefined
    at login (C:\Users\m273p\Desktop\hideSpamBot-main\script.js:24:56)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

이런 에러가 생기는데 뭐가 문제인지 감이 안와요 ㅠㅠ
도와주세요

**Comment by heeboom** [comment]
왜 그런지 알아냈습니다.
코드 쉐어해주셔서 감사합니다.

**Comment by wiresharkkkk** [comment]
@heeboom  어떻게 해결하셨는지 저도 알 수 있을까요..?
